In [1]:
  import pandas as pd
  print(pd.__version__)

3.0.6

In [8]:
STOPS_PATH = "../data/raw/itm_north_west_gtfs/stops.txt"
df = pd.read_csv(STOPS_PATH,dtype={"stop_id": str, "stop_code": str})
df.head()

,stop_id,stop_code,stop_name,stop_lat,stop_lon,wheelchair_boarding,location_type,parent_station,platform_code
0,2500DCL792,landmwdg,New Line,53.690549,-2.182164,0,0,NaN,NaN
1,090033104077,cumdpjmt,Ness Way,54.884603,-2.968188,0,0,NaN,NaN
2,0600MA19191,cheagjap,Smith Lane,53.331856,-2.339258,0,0,NaN,NaN
3,2800S44079B,merdmpjg,Eaton Road,53.430030,-2.909250,0,0,NaN,NaN
4,2500IMG2876,langjdpa,Rosehill Road,53.782133,-2.253631,0,0,NaN,NaN

In [11]:
df.shape

(36785, 9)

In [13]:
df.isnull().sum()

stop_id                    0
stop_code               1941
stop_name                  0
stop_lat                   0
stop_lon                   0
wheelchair_boarding        0
location_type              0
parent_station         36082
platform_code          36255
dtype: int64

In [14]:
df.describe()

           stop_lat      stop_lon  wheelchair_boarding  location_type
count  36785.000000  36785.000000              36785.0    36785.00000
mean      53.624556     -2.583132                  0.0        0.00560
std        0.413776      0.370889                  0.0        0.07535
min       51.156573     -4.251747                  0.0        0.00000
25%       53.403710     -2.900430                  0.0        0.00000
50%       53.514449     -2.576561                  0.0        0.00000
75%       53.733254     -2.255969                  0.0        0.00000
max       55.955515     -0.060961                  0.0        2.00000